[package]
name = "bytesklad"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/makcandrov/bytesklad"
homepage = "https://github.com/makcandrov/bytesklad"
license = "MIT OR Apache-2.0"
description = "Insert-only embedded database mapping fixed-size keys to variable-size byte values, ordered by key."
keywords = ["database", "embedded", "key-value", "append-only", "storage"]
categories = ["database-implementations"]

[dependencies]
indexmap = "2"
libmdbx = "0.9"
parking_lot = "0.12"
rustc-hash = "2"
thiserror = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_System_IO",
] }

[dev-dependencies]
tempfile = "3"
