[workspace]
members = ["crates/*"]
default-members = ["crates/preimages-db"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/makcandrov/preimages-db"
homepage = "https://github.com/makcandrov/preimages-db"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
preimages-db = { path = "crates/preimages-db" }
flat-store = { path = "crates/flat-store" }

hashbrown = "0.17"
parking_lot = "0.12"
libmdbx = "0.6"
thiserror = "2"
tempfile = "3"
tiny-keccak = { version = "2", features = ["keccak"] }
libc = "0.2"
windows-sys = "0.61"
