[package]
name = "preimages-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
flat-store.workspace = true
libmdbx.workspace = true
thiserror.workspace = true
sdecode-preimages-interface = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true
tiny-keccak.workspace = true

[features]
sdecode = ["dep:sdecode-preimages-interface"]
